Hw4
ok-technopolis-2021/Scheredin-Artyom pull request #4
Opened 2021-11-12 09:53 UTC by ArtyomScheredin

2021-11-22 07:51 UTC, BusinessDuck requested changes

2021-11-22 07:51 UTC, BusinessDuck commented on dist/index.html
> +  <link rel="stylesheet" type="text/css" href="/src/styles/style.css">
ссылка на стили в SRC, в папке dist, -1 балл, это серьезная ошибка

2021-11-22 07:51 UTC, BusinessDuck commented on src/index.html
> +  <link rel="stylesheet" type="text/css" href="/src/styles/style.css">
еще -0.5 баллов, забыта строчка для установки автоимпорта стилей, как в примере, что я давал

2021-11-22 07:51 UTC, BusinessDuck commented on gulpfile.js
> +const stylesPath = './src/styles/**/*.scss';
не все файлы переименованы в scss, -0.2 балла, все файлы должны быть иметь расширение scss, по крайней мере те, что мы сами пишем, IDE определяет синтаксис по расширению файла, и если мы не используем активно возможности scss, файлы все равно нужно переименовать, ну и желательно использовать все таки хотя бы вложенность селекторов

2021-11-22 07:51 UTC, BusinessDuck commented
8.5 Баллов, нужно доделать правки и еще раз прислать запрос на ревью

2021-11-22 11:15 UTC, ArtyomScheredin commented on .idea/.gitignore
> +# Default ignored files
Добавил .idea в игнор

2021-11-22 11:15 UTC, ArtyomScheredin commented on dist/index.html
> +  <link rel="stylesheet" type="text/css" href="/src/styles/style.css">
убрал ссылки на стили и скрипты из index.html

2021-11-22 11:15 UTC, ArtyomScheredin commented on src/index.html
> +  <link rel="stylesheet" type="text/css" href="/src/styles/style.css">
Добавил необходимые строки

2021-11-22 11:16 UTC, ArtyomScheredin commented on gulpfile.js
> +const stylesPath = './src/styles/**/*.scss';
исправил

2021-11-23 09:22 UTC, BusinessDuck approved these changes
Стало получше, спасибо

2021-12-08 19:13 UTC, merged